---
apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
spec:
  destination:
    namespace: jenkins
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argoselfmanaged/jenkins
    repoURL: https://github.com/coryleeio/k8sdev
    targetRevision: HEAD
  helm:
    valueFiles:
      - values.yaml
  syncPolicy:
    automated: {}
