apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
spec:
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  project: default
  source:
    path: vault
    repoURL: https://github.com/coryleeio/k8sdev/argoselfmanaged
    targetRevision: HEAD
