---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
spec:
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argoselfmanaged/vault
    repoURL: https://github.com/coryleeio/k8sdev
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
