bases: 
  - ../argocd/
  - ../vault
  - ../jenkins
namespace: argocd
namePrefix: tools-
patchesJSON6902:
- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: jenkins
  path: jenkins-patch.yaml
