---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meta-pipeline
spec:
  destination:
    namespace: meta-pipeline
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argoselfmanaged/argocd-applications/overlays/development
    repoURL: https://github.com/coryleeio/k8sdev
    targetRevision: HEAD
  syncPolicy:
    automated: {}
