apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
spec:
  project: default
  source:
    repoURL: 'https://kubernetes-charts.storage.googleapis.com'
    chart: mysql
    targetRevision: 1.6.0
    helm:
      valueFiles:
        - values.yaml
      values: |
        ingress:
          enabled: false
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

